# Generated by Django 2.2.3 on 2019-07-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=300)),
                ('task_des', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('ctg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worksheet.Type')),
            ],
        ),
    ]
