# Generated by Django 2.2.3 on 2019-08-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0002_todo_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
