# Generated by Django 2.2.3 on 2019-08-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personal', models.CharField(max_length=15)),
                ('home_num', models.CharField(max_length=15)),
                ('office_num', models.CharField(max_length=15)),
                ('email_num', models.EmailField(max_length=254)),
                ('about_person', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_book.Category')),
            ],
        ),
    ]
