# Generated by Django 2.2.3 on 2019-08-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0002_auto_20190803_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonebookmodel',
            old_name='email_num',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='phonebookmodel',
            old_name='home_num',
            new_name='home_number',
        ),
        migrations.RenameField(
            model_name='phonebookmodel',
            old_name='office_num',
            new_name='office_number',
        ),
        migrations.RenameField(
            model_name='phonebookmodel',
            old_name='personal_num_new',
            new_name='personal_number',
        ),
    ]
