# Generated by Django 2.2.3 on 2019-09-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albummodel',
            old_name='image',
            new_name='img',
        ),
    ]
