# Generated by Django 2.2.3 on 2019-07-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryCtg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('diary_text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('diary_ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary_app.DiaryCtg')),
            ],
        ),
    ]
